### ISSUE TITLE
Cannot get link with video fullhd

### ISSUE THREAD

**Issue by tienanhbui** [Maadhav/youtube-downloader-API#2]
Video fullhd return 403 when result link access. SignatureDecoder not work as expected
ex: https://www.youtube.com/watch?v=NUsoVlDFqZg

**Comment by tienanhbui** [comment]
I am reading function `decode` in `SignatureDecoder` class. Can you explain about this function?

**Comment by Maadhav** [comment]
Actually This project is originally forked from https://github.com/Athlon1600/youtube-downloader
I have only done the frontend UI changes and more easily accessible API of the download links. It would be better to post this issue in his repo. https://github.com/Athlon1600/youtube-downloader/issues
Thanks
