### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by GokulNC** [Maadhav/youtube-downloader-API#9]
Thanks for this work!

Can you enable please CORS in the server?

When I am hitting the endpoint from my frontend, it gives
> Access to XMLHttpRequest at 'https://maadhav-ytdl.herokuapp.com/video_info.php?url=https://www.youtube.com/watch?v=BaW_jenozKc' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by GokulNC** [comment]
Though I do not know PHP, something like this should be sufficient I believe:

https://stackoverflow.com/a/40632753/

**Comment by Maadhav** [comment]
@GokulNC Maintaining this repository is not being actively maintained, you should check out https://github.com/Athlon1600/youtube-downloader or create a pull request in this repo if interested. 
Thanks
